apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-config
  namespace: default
data:
  RABBITMQ_QUEUE: 'HeatSensor'
  RABBITMQ_HOST: rabbitmq-broker
  RABBITMQ_PORT: "5672"
  RABBITMQ_PROTOCOL: "amqp"
  POSTGRES_HOST: 'psql-database'
  PORT: "3001"
  FREQUENCY: "50000"
---
apiVersion: v1
kind: Service
metadata:
  name: consumer
  namespace: default
spec:
  selector:
    app: consumer
  ports:
    - name: consumer
      protocol: TCP
      port: 3001
      targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: default
  labels: 
    app: consumer
spec:
  selector:
    matchLabels:
      app: consumer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: nathapaulino/aps_consumer
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: consumer-config
        - secretRef:
            name: consumer-secrets
---